# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SDG_15_1_2_calculator
                                 A QGIS plugin
 Proportion of important sites for terrestrial and freshwater biodiversity that are covered by protected areas, by ecosystem type
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-07-14
        copyright            : (C) 2022 by IIA-CNR
        email                : aquilino@iia.cnr.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'IIA-CNR'
__date__ = '2022-07-14'
__copyright__ = '(C) 2022 by IIA-CNR'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SDG_15_1_2_calculator class from file SDG_15_1_2_calculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SDG_15_1_2_calculator import SDG_15_1_2_calculatorPlugin
    return SDG_15_1_2_calculatorPlugin()
